apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - audit-cleartext-env-values.yaml
  - disallow-host-network.yaml
  - disallow-root-containers.yaml
  - require-workload-controls.yaml
  - restrict-image-references.yaml
  - restrict-service-exposure.yaml
  - restrict-volume-types.yaml
