apiVersion: v1
kind: Secret
metadata:
  name: securerag-database-secrets
  namespace: securerag-hub
type: Opaque
stringData:
  DB_CONNECTION: pgsql
  DB_HOST: change-me-postgres-host
  DB_PORT: "5432"
  DB_USERNAME: change-me-postgres-user
  DB_PASSWORD: change-me-minimum-20-characters
  DB_SSLMODE: require
  PORTAL_WEB_DB_DATABASE: portal_web
  AUTH_USERS_DB_DATABASE: auth_users
  CHATBOT_MANAGER_DB_DATABASE: chatbot_manager
  CONVERSATION_SERVICE_DB_DATABASE: conversation_service
  AUDIT_SECURITY_SERVICE_DB_DATABASE: audit_security
