apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: portal-web-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: portal-web
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - podSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - auth-users
                  - chatbot-manager
                  - conversation-service
                  - audit-security-service
      ports:
        - protocol: TCP
          port: 8000
