apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: securerag-chaos-pod-kill
  namespace: chaos-testing
spec:
  schedule: "@every 5m"
  type: PodChaos
  historyLimit: 2
  concurrencyPolicy: Forbid
  podChaos:
    action: pod-kill
    mode: one
    selector:
      namespaces:
        - securerag-test
      labelSelectors:
        app.kubernetes.io/name: auth-users
    duration: "30s"
