#!/usr/bin/env bash
# Pin Kustomize overlay images to digests produced by the CD pipeline.
#
# Reads `artifacts/release/promotion-digests.txt` (one line per service,
# format: `service|registry/name@sha256:...`) and rewrites the `images:`
# block of the target overlay to use `digest:` instead of `newTag:`.
#
# Usage:
#   bash scripts/release/pin-overlay-digests.sh \
#     --overlay infra/k8s/overlays/production \
#     [--digest-file artifacts/release/promotion-digests.txt] \
#     [--commit] [--dry-run]
#
# Idempotent: re-running with same digests is a no-op.
# Safe-by-default: prints diff and exits unless --commit is passed.

set -euo pipefail

OVERLAY=""
DIGEST_FILE="artifacts/release/promotion-digests.txt"
COMMIT="false"
DRY_RUN="false"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --overlay)      OVERLAY="$2"; shift 2 ;;
    --digest-file)  DIGEST_FILE="$2"; shift 2 ;;
    --commit)       COMMIT="true"; shift ;;
    --dry-run)      DRY_RUN="true"; shift ;;
    -h|--help)
      sed -n '2,18p' "$0"; exit 0 ;;
    *) echo "[ERROR] Unknown arg: $1" >&2; exit 2 ;;
  esac
done

[ -n "${OVERLAY}" ] || { echo "[ERROR] --overlay required" >&2; exit 2; }
[ -f "${OVERLAY}/kustomization.yaml" ] || { echo "[ERROR] kustomization.yaml not found in ${OVERLAY}" >&2; exit 2; }
[ -s "${DIGEST_FILE}" ] || { echo "[ERROR] digest file empty/missing: ${DIGEST_FILE}" >&2; exit 2; }

command -v yq >/dev/null 2>&1 || {
  echo "[ERROR] 'yq' (mikefarah) is required. Install: https://github.com/mikefarah/yq" >&2
  exit 2
}

KUST="${OVERLAY}/kustomization.yaml"
TMP="$(mktemp)"
trap 'rm -f "${TMP}"' EXIT

cp "${KUST}" "${TMP}"

# Process each digest line
while IFS='|' read -r service ref; do
  [ -z "${service}" ] && continue
  [ -z "${ref}" ] && continue

  # Expected ref: registry/name@sha256:HEX
  if [[ "${ref}" != *"@sha256:"* ]]; then
    echo "[WARN] line for '${service}' does not contain @sha256, skipping: ${ref}" >&2
    continue
  fi

  name="${ref%@*}"      # registry/name
  digest="@${ref#*@}"   # @sha256:...
  digest_value="${digest#@}" # sha256:...

  # We match the upstream image NAME column (newName preferred; else name).
  # The Kustomization has e.g.:
  #   - name: ghcr.io/example/securerag-hub-portal-web
  #     newName: localhost:5001/securerag-hub-portal-web
  #     newTag: production
  # We replace newTag → digest.

  # Find index of an entry whose newName ends with the service basename
  # (or whose name does), then patch.
  basename_service="$(basename "${name}")"

  idx=$(yq eval ".images | to_entries | .[] | select(.value.newName == \"${name}\" or .value.name | test(\"${basename_service}$\")) | .key" "${TMP}" | head -1 || true)
  if [ -z "${idx}" ]; then
    echo "[WARN] no images[] entry matched ${name} (basename=${basename_service}); skipping" >&2
    continue
  fi

  yq eval -i ".images[${idx}].newName = \"${name}\"" "${TMP}"
  yq eval -i "del(.images[${idx}].newTag)" "${TMP}"
  yq eval -i ".images[${idx}].digest = \"${digest_value}\"" "${TMP}"
  echo "[OK] images[${idx}] (${basename_service}) → digest=${digest_value}"
done < "${DIGEST_FILE}"

echo
echo "===== diff ====="
if diff -u "${KUST}" "${TMP}" || true; then :; fi
echo "================"

if [ "${DRY_RUN}" = "true" ]; then
  echo "[INFO] --dry-run set; not writing changes."
  exit 0
fi

if cmp -s "${KUST}" "${TMP}"; then
  echo "[INFO] No changes — overlay already pinned to these digests."
  exit 0
fi

cp "${TMP}" "${KUST}"
echo "[OK] Overlay updated: ${KUST}"

if [ "${COMMIT}" = "true" ]; then
  if ! git -C "$(dirname "${OVERLAY}")" rev-parse >/dev/null 2>&1; then
    echo "[WARN] not a git repo, skipping commit"
    exit 0
  fi
  git add "${KUST}"
  git commit -m "ci(cd): pin overlay $(basename "${OVERLAY}") to verified digests" \
    -m "Source: ${DIGEST_FILE}" \
    -m "Generated by scripts/release/pin-overlay-digests.sh"
  echo "[OK] Committed."
fi
