apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-auth-users
  namespace: securerag-hub
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::<PLACEHOLDER_AWS_ACCOUNT_ID>:role/securerag-auth-users-role"
