apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-web
spec:
  template:
    spec:
      containers:
        - name: portal-web
          env:
            - name: PORTAL_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: portal-admin-token
                  key: token
