apiVersion: v1
kind: ResourceQuota
metadata:
  name: securerag-hub-quota
spec:
  hard:
    pods: "60"
    services: "30"
    persistentvolumeclaims: "20"
    requests.cpu: "8"
    limits.cpu: "20"
    requests.memory: 8Gi
    limits.memory: 24Gi
    requests.ephemeral-storage: 12Gi
    limits.ephemeral-storage: 36Gi
    requests.storage: 100Gi
