apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: securerag-database-secrets
  namespace: securerag-hub
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: securerag-database-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: DB_CONNECTION
      remoteRef:
        key: kv/data/securerag-hub/production/db
        property: DB_CONNECTION
    - secretKey: DB_HOST
      remoteRef:
        key: kv/data/securerag-hub/production/db
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: kv/data/securerag-hub/production/db
        property: DB_PORT
    - secretKey: DB_USERNAME
      remoteRef:
        key: kv/data/securerag-hub/production/db
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: kv/data/securerag-hub/production/db
        property: DB_PASSWORD
    - secretKey: DB_SSLMODE
      remoteRef:
        key: kv/data/securerag-hub/production/db
        property: DB_SSLMODE
    - secretKey: PORTAL_WEB_DB_DATABASE
      remoteRef:
        key: kv/data/securerag-hub/production/db
        property: PORTAL_WEB_DB_DATABASE
    - secretKey: AUTH_USERS_DB_DATABASE
      remoteRef:
        key: kv/data/securerag-hub/production/db
        property: AUTH_USERS_DB_DATABASE
    - secretKey: CHATBOT_MANAGER_DB_DATABASE
      remoteRef:
        key: kv/data/securerag-hub/production/db
        property: CHATBOT_MANAGER_DB_DATABASE
    - secretKey: CONVERSATION_SERVICE_DB_DATABASE
      remoteRef:
        key: kv/data/securerag-hub/production/db
        property: CONVERSATION_SERVICE_DB_DATABASE
    - secretKey: AUDIT_SECURITY_SERVICE_DB_DATABASE
      remoteRef:
        key: kv/data/securerag-hub/production/db
        property: AUDIT_SECURITY_SERVICE_DB_DATABASE
