apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - eso-cluster-secret-store.yaml
  - example-external-secret.yaml
  - grafana-external-secret.yaml
  - argocd-notifications-external-secret.yaml
  - securerag-common-secrets.yaml
