apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-velero-credentials
  namespace: velero
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vault-velero-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: cloud
      remoteRef:
        key: securerag/velero
        property: cloud
