apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-sbom-attestation
  labels:
    app.kubernetes.io/part-of: securerag-hub
    app.kubernetes.io/managed-by: kyverno
  annotations:
    policies.kyverno.io/title: Verify SBOM Attestation
    policies.kyverno.io/category: Supply Chain Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Every container image in securerag-hub must have a valid SBOM (Software
      Bill of Materials) attestation attached.
spec:
  validationFailureAction: Enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: verify-sbom
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - securerag-hub
      verifyImages:
        - imageReferences:
            - "localhost:5001/securerag-hub-*"
            - "harbor.securerag.local/securerag-hub/*"
          mutateDigest: true
          verifyDigest: true
          required: true
          attestors:
            - count: 1
              entries:
                - keyless:
                    issuer: https://keycloak.sigstore-system/realms/securerag-cicd
                    subject: jenkins-cosign@securerag.local
                    roots: |
@FULCIO_ROOT@
                    rekor:
                      url: https://rekor.sigstore-system
                      pubkey: |
@REKOR_PUBKEY@
          attestations:
            - predicateType: https://spdx.dev/Document
              attestors:
                - count: 1
                  entries:
                    - keyless:
                        issuer: https://keycloak.sigstore-system/realms/securerag-cicd
                        subject: jenkins-cosign@securerag.local
                        roots: |
@FULCIO_ROOT_A1@
                        rekor:
                          url: https://rekor.sigstore-system
                          pubkey: |
@REKOR_PUBKEY_A1@
            - predicateType: https://cyclonedx.org/bom
              attestors:
                - count: 1
                  entries:
                    - keyless:
                        issuer: https://keycloak.sigstore-system/realms/securerag-cicd
                        subject: jenkins-cosign@securerag.local
                        roots: |
@FULCIO_ROOT_A2@
                        rekor:
                          url: https://rekor.sigstore-system
                          pubkey: |
@REKOR_PUBKEY_A2@
