apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: securerag-vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: securerag-hub
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.29.0
    chart: vault
    helm:
      values: "server:\n  tolerations:\n  - key: node-role.kubernetes.io/control-plane\n\
        \    operator: Exists\n    effect: NoSchedule\n  - key: node-role.kubernetes.io/master\n\
        \    operator: Exists\n    effect: NoSchedule\n  affinity: null\ninjector:\n\
        \  enabled: true\nui:\n  enabled: true\n  serviceType: ClusterIP\n"
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[].clientConfig.caBundle
