apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: securerag-dr-multicluster
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          securerag: 'true'
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: '35'
        notifications.argoproj.io: on-deployed,on-health-degraded,on-sync-failed
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      labels:
        app.kubernetes.io/component: disaster-recovery
        app.kubernetes.io/part-of: securerag-hub
      name: securerag-dr-{{name}}
    spec:
      destination:
        namespace: securerag-hub-dr
        server: '{{server}}'
      project: securerag-hub
      source:
        path: infra/k8s/dr-validation
        repoURL: https://github.com/YassinoMed/MasterPFE.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
          limit: 5
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
