apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: securerag-hub
  name: securerag-all-services
  namespace: argocd
spec:
  generators:
  - git:
      directories:
      - path: infra/k8s/environments/*
      repoURL: https://github.com/YassinoMed/MasterPFE.git
      revision: main
  - list:
      elements:
      - env: demo
        namespace: securerag-hub
        path: infra/k8s/overlays/demo
        wave: '10'
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
        notifications.argoproj.io: on-deployed,on-health-degraded,on-sync-failed,on-out-of-sync
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      name: securerag-{{path.basename}}
    spec:
      destination:
        namespace: securerag-{{path.basename}}
        server: https://kubernetes.default.svc
      ignoreDifferences:
      - group: external-secrets.io
        jqPathExpressions:
        - .metadata.annotations["reconcile.external-secrets.io/data-hash"]
        - .spec.target.creationPolicy
        - .spec.target.deletionPolicy
        - .spec.binding
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
        - .spec.dataFrom[].extract.conversionStrategy
        - .spec.dataFrom[].extract.decodingStrategy
        - .spec.dataFrom[].extract.metadataPolicy
        kind: ExternalSecret
      - group: apps
        jqPathExpressions:
        - .spec.replicas
        kind: Deployment
      project: securerag-hub
      revisionHistoryLimit: 10
      source:
        path: infra/k8s/overlays/{{path.basename}}
        repoURL: https://github.com/YassinoMed/MasterPFE.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
          limit: 5
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
