apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: securerag-platform
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: observability
        namespace: securerag-monitoring
        path: infra/k8s/observability
        wave: '30'
      - name: otel
        namespace: otel-system
        path: infra/k8s/otel
        wave: '31'
      - name: backup
        namespace: securerag-backup
        path: infra/k8s/backup
        wave: '40'
      - name: runtime-detection
        namespace: falco
        path: infra/k8s/runtime-detection
        wave: '4'
      - name: kyverno
        namespace: kyverno
        path: infra/k8s/addons/kyverno
        wave: '5'
      - name: kyverno-policies
        namespace: kyverno
        path: infra/k8s/policies/kyverno
        wave: '6'
      - name: metrics-server
        namespace: kube-system
        path: infra/k8s/addons/metrics-server
        wave: '10'
      - name: secrets
        namespace: external-secrets
        path: infra/k8s/secrets
        wave: '15'
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
        notifications.argoproj.io: on-deployed,on-health-degraded,on-sync-failed,on-out-of-sync
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      name: securerag-{{name}}
    spec:
      destination:
        namespace: '{{namespace}}'
        server: https://kubernetes.default.svc
      ignoreDifferences:
      - group: external-secrets.io
        jqPathExpressions:
        - .metadata.annotations["reconcile.external-secrets.io/data-hash"]
        - .spec.target.creationPolicy
        - .spec.target.deletionPolicy
        - .spec.binding
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
        - .spec.dataFrom[].extract.conversionStrategy
        - .spec.dataFrom[].extract.decodingStrategy
        - .spec.dataFrom[].extract.metadataPolicy
        kind: ExternalSecret
      - group: apps
        jqPathExpressions:
        - .spec.replicas
        kind: Deployment
      - group: kyverno.io
        jsonPointers:
        - /spec/rules/0/allowExistingViolations
        - /spec/rules/0/generate
        - /spec/rules/0/skipBackgroundRequests
        - /spec/rules/1/allowExistingViolations
        - /spec/rules/1/generate
        - /spec/rules/1/skipBackgroundRequests
        kind: ClusterPolicy
      project: securerag-hub
      source:
        path: '{{path}}'
        repoURL: https://github.com/YassinoMed/MasterPFE.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
