# ApplicationSet — Platform (infrastructure core)
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: securerag-platform
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: cert-manager
            path: infra/k8s/argocd
            namespace: cert-manager
            wave: "3"
            chart: false
          - name: kyverno
            path: infra/k8s/addons/kyverno
            namespace: kyverno
            wave: "5"
            chart: false
          - name: kyverno-policies
            path: infra/k8s/policies/kyverno-enforce
            namespace: kyverno
            wave: "6"
            chart: false
          - name: metrics-server
            path: infra/k8s/addons/metrics-server
            namespace: kube-system
            wave: "10"
            chart: false
          - name: secrets
            path: infra/k8s/secrets
            namespace: external-secrets
            wave: "15"
            chart: false
  template:
    metadata:
      name: 'securerag-{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: securerag-hub
      source:
        repoURL: https://github.com/YassinoMed/MasterPFE.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        retry:
          limit: 10
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
