apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
data:
  statusbadge.enabled: "true"
  timeout.reconciliation: "180s"
  application.instanceLabelKey: argocd.argoproj.io/instance
