FROM python:3.12-slim

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install requirements
RUN pip install --no-cache-dir httpx kubernetes

# Copy daemon script
COPY log_collector.py .

ENV PYTHONUNBUFFERED=1
ENV BACKEND_URL=http://10.15.10.119:8082
ENV MOCK_LOGS=true

USER 65534:65534

CMD ["python", "log_collector.py"]
