#!/usr/bin/env bash
# security/tests/kyverno-audit-report.sh
# Performs a Kyverno Enforce dry-run audit against active pods and generates an HTML report.

set -euo pipefail

KYVERNO_VERSION="v1.12.5"
POLICY_DIR="k8s/kyverno-policies/enforce"
AUDIT_DIR="/tmp/kyverno-audit"
REPORT_HTML="security/reports/kyverno-audit-report.html"

echo "=== KYVERNO ENFORCE DRY-RUN AUDIT ==="

# 1. Ensure Kyverno CLI is installed
if ! command -v kyverno &> /dev/null; then
    echo "[INFO] Kyverno CLI not found. Downloading version ${KYVERNO_VERSION}..."
    curl -Lo /tmp/kyverno.tar.gz "https://github.com/kyverno/kyverno/releases/download/${KYVERNO_VERSION}/kyverno-cli_${KYVERNO_VERSION}_linux_x86_64.tar.gz"
    tar -xzf /tmp/kyverno.tar.gz -C /tmp
    mv /tmp/kyverno /usr/local/bin/kyverno
    chmod +x /usr/local/bin/kyverno
    rm -f /tmp/kyverno.tar.gz
    echo "[OK] Kyverno CLI installed successfully."
else
    echo "[OK] Kyverno CLI is already installed: $(kyverno version | grep Version || true)"
fi

# 2. Extract manifests from the cluster
echo "[INFO] Extracting active pods from cluster (namespaces: securerag-hub, recette)..."
rm -rf "$AUDIT_DIR"
mkdir -p "$AUDIT_DIR"

kubectl get pods -n securerag-hub -o yaml > "$AUDIT_DIR/securerag-hub-pods.yaml" 2>/dev/null || echo "---" > "$AUDIT_DIR/securerag-hub-pods.yaml"
kubectl get pods -n recette -o yaml > "$AUDIT_DIR/recette-pods.yaml" 2>/dev/null || echo "---" > "$AUDIT_DIR/recette-pods.yaml"

# Remove status and metadata fields that are not relevant to validation to clean up the dry-run
# (Kyverno CLI can handle them, but cleaning metadata avoids clutter)
python3 -c "
import yaml, sys, os
for f in os.listdir('$AUDIT_DIR'):
    if not f.endswith('.yaml'): continue
    path = os.path.join('$AUDIT_DIR', f)
    try:
        with open(path, 'r') as file:
            content = yaml.safe_load(file)
        os.remove(path)
        if content and 'items' in content:
            for idx, item in enumerate(content['items']):
                if 'status' in item: del item['status']
                if 'metadata' in item:
                    meta = item['metadata']
                    for key in ['uid', 'resourceVersion', 'creationTimestamp', 'managedFields', 'ownerReferences']:
                        if key in meta: del meta[key]
                new_path = os.path.join('$AUDIT_DIR', f'pod-{f}-{idx}.yaml')
                with open(new_path, 'w') as new_file:
                    yaml.safe_dump(item, new_file)
    except Exception as e:
        print(f'Warning cleaning/unpacking {f}: {e}')
"

# 3. Simulate Enforce mode via dry-run using Kyverno CLI
echo "[INFO] Running Kyverno CLI apply and generating policy report..."
# Use wildcard to load all policies to bypass directory load limitations in some CLI versions
kyverno apply "$POLICY_DIR"/*.yaml --resource "$AUDIT_DIR" --policy-report > "$AUDIT_DIR/report.yaml" 2>/dev/null || true

# 4. Process report and generate HTML using Python
echo "[INFO] Compiling results and generating HTML report..."
mkdir -p "$(dirname "$REPORT_HTML")"

python3 -c "
import yaml
import sys
import os
import datetime

report_path = '$AUDIT_DIR/report.yaml'
html_path = '$REPORT_HTML'

if not os.path.exists(report_path):
    print('[ERROR] Policy report not generated by Kyverno CLI.')
    sys.exit(1)

with open(report_path, 'r') as f:
    report = yaml.safe_load(f)

if not report:
    report = {}

results = report.get('results', [])
summary = report.get('summary', {'pass': 0, 'fail': 0, 'warn': 0, 'error': 0, 'skip': 0})

all_pods = set()
failed_pods = set()
violations = []

for res in results:
    status = res.get('result')
    policy = res.get('policy')
    rule = res.get('rule')
    message = res.get('message')
    
    resources = res.get('resources', [])
    if not resources:
        continue
    resource = resources[0]
    kind = resource.get('kind')
    name = resource.get('name')
    namespace = resource.get('namespace', 'default')
    
    if kind != 'Pod':
        continue
        
    pod_id = f'{namespace}/{name}'
    all_pods.add(pod_id)
    
    if status == 'fail':
        failed_pods.add(pod_id)
        violations.append({
            'namespace': namespace,
            'pod': name,
            'policy': policy,
            'rule': rule,
            'message': message
        })

total_pods = len(all_pods)
failed_pods_count = len(failed_pods)
compliant_pods_count = total_pods - failed_pods_count

if total_pods > 0:
    compliance_score = (compliant_pods_count * 100) // total_pods
else:
    compliance_score = 100

date_str = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')

score_color = 'var(--color-pass)'
if compliance_score < 50:
    score_color = 'var(--color-fail)'
elif compliance_score < 80:
    score_color = 'var(--color-warn)'

fail_color_style = 'color: var(--color-fail)' if failed_pods_count > 0 else 'color: var(--text-primary)'

table_body = ''
if violations:
    table_body = '<table><thead><tr><th>Namespace</th><th>Pod</th><th>Politique</th><th>Règle</th><th>Message d\\'erreur</th></tr></thead><tbody>'
    for v in violations:
        table_body += f'''<tr>
            <td><code>{v['namespace']}</code></td>
            <td><strong>{v['pod']}</strong></td>
            <td><code>{v['policy']}</code></td>
            <td><code>{v['rule']}</code></td>
            <td><span class=\"status-fail\">{v['message']}</span></td>
        </tr>'''
    table_body += '</tbody></table>'
else:
    table_body = '<div style=\"padding: 2rem; text-align: center; color: var(--text-secondary);\">Aucune violation détectée ! Tous les pods sont conformes.</div>'

html_content = f'''<!DOCTYPE html>
<html lang=\"fr\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>Rapport d\\'Audit de Sécurité Kyverno</title>
    <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700&display=swap\" rel=\"stylesheet\">
    <style>
        :root {{
            --bg-main: #0f172a;
            --bg-card: #1e293b;
            --text-primary: #f8fafc;
            --text-secondary: #94a3b8;
            --color-pass: #10b981;
            --color-fail: #ef4444;
            --color-warn: #f59e0b;
            --color-info: #3b82f6;
            --border-color: #334155;
        }}
        
        * {{
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }}
        
        body {{
            font-family: \\'Outfit\\', sans-serif;
            background-color: var(--bg-main);
            color: var(--text-primary);
            line-height: 1.6;
            padding: 2rem;
        }}
        
        .container {{
            max-width: 1200px;
            margin: 0 auto;
        }}
        
        header {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 2rem;
            border-bottom: 1px solid var(--border-color);
            padding-bottom: 1.5rem;
        }}
        
        h1 {{
            font-size: 2.2rem;
            font-weight: 700;
            background: linear-gradient(135deg, #38bdf8, #818cf8);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }}
        
        .badge {{
            background-color: var(--bg-card);
            border: 1px solid var(--border-color);
            padding: 0.5rem 1rem;
            border-radius: 9999px;
            font-size: 0.85rem;
            color: var(--text-secondary);
        }}
        
        .dashboard {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
            gap: 1.5rem;
            margin-bottom: 2rem;
        }}
        
        .card {{
            background-color: var(--bg-card);
            border: 1px solid var(--border-color);
            border-radius: 12px;
            padding: 1.5rem;
            text-align: center;
            box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1);
            transition: transform 0.2s;
        }}
        
        .card:hover {{
            transform: translateY(-4px);
        }}
        
        .card-title {{
            font-size: 0.9rem;
            color: var(--text-secondary);
            margin-bottom: 0.5rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }}
        
        .card-value {{
            font-size: 2.5rem;
            font-weight: 700;
        }}
        
        .score-gauge {{
            width: 100%;
            height: 10px;
            background-color: var(--border-color);
            border-radius: 5px;
            margin-top: 1rem;
            overflow: hidden;
        }}
        
        .score-fill {{
            height: 100%;
            background: linear-gradient(90deg, var(--color-fail), var(--color-pass));
            border-radius: 5px;
        }}
        
        .table-container {{
            background-color: var(--bg-card);
            border: 1px solid var(--border-color);
            border-radius: 12px;
            overflow: hidden;
            margin-bottom: 2rem;
        }}
        
        table {{
            width: 100%;
            border-collapse: collapse;
            text-align: left;
        }}
        
        th {{
            background-color: rgba(51, 65, 85, 0.5);
            padding: 1rem;
            font-weight: 600;
            border-bottom: 1px solid var(--border-color);
            font-size: 0.9rem;
            color: var(--text-secondary);
        }}
        
        td {{
            padding: 1rem;
            border-bottom: 1px solid var(--border-color);
            font-size: 0.95rem;
        }}
        
        tr:last-child td {{
            border-bottom: none;
        }}
        
        .status-fail {{
            color: var(--color-fail);
            font-weight: 600;
            background-color: rgba(239, 68, 68, 0.1);
            padding: 0.25rem 0.5rem;
            border-radius: 6px;
            display: inline-block;
        }}
        
        .remediation-section {{
            background-color: var(--bg-card);
            border: 1px solid var(--border-color);
            border-radius: 12px;
            padding: 1.5rem;
        }}
        
        .remediation-title {{
            font-size: 1.25rem;
            font-weight: 600;
            margin-bottom: 1rem;
            color: #38bdf8;
        }}
        
        .remediation-list {{
            list-style-position: inside;
            color: var(--text-secondary);
        }}
        
        .remediation-list li {{
            margin-bottom: 0.75rem;
        }}
    </style>
</head>
<body>
    <div class=\"container\">
        <header>
            <div>
                <h1>Rapport d\\'Audit Kyverno</h1>
                <p style=\"color: var(--text-secondary); margin-top: 0.25rem;\">Simulation du mode Enforce sur les pods du cluster</p>
            </div>
            <div class=\"badge\">Généré le: {date_str}</div>
        </header>
        
        <div class=\"dashboard\">
            <div class=\"card\">
                <div class=\"card-title\">Compliance Score</div>
                <div class=\"card-value\" style=\"color: {score_color}\">{compliance_score}%</div>
                <div class=\"score-gauge\">
                    <div class=\"score-fill\" style=\"width: {compliance_score}%\"></div>
                </div>
            </div>
            <div class=\"card\">
                <div class=\"card-title\">Pods Analysés</div>
                <div class=\"card-value\">{total_pods}</div>
            </div>
            <div class=\"card\">
                <div class=\"card-title\">Pods Conformes</div>
                <div class=\"card-value\" style=\"color: var(--color-pass)\">{compliant_pods_count}</div>
            </div>
            <div class=\"card\">
                <div class=\"card-title\">Pods Non-Conformes</div>
                <div class=\"card-value\" style=\"{fail_color_style}\">{failed_pods_count}</div>
            </div>
        </div>
        
        <h2 style=\"margin-bottom: 1rem; font-weight: 600;\">Détail des Violations ({len(violations)})</h2>
        
        <div class=\"table-container\">
            {table_body}
        </div>
        
        <div class=\"remediation-section\">
            <div class=\"remediation-title\">Plan d\\'Action de Remédiation Recommandé</div>
            <ul class=\"remediation-list\">
                <li><strong>POLICY 1 (Root Containers)</strong> : Modifier les templates de Pods dans les charts Helm/Kustomize pour ajouter <code>securityContext.runAsNonRoot: true</code> et <code>securityContext.runAsUser: 10001</code>.</li>
                <li><strong>POLICY 3 (Digest SHA256)</strong> : Modifier la pipeline de release pour pousser les manifests avec des digests d\\'images plutôt que des tags mutables.</li>
                <li><strong>POLICY 4 (Ressources CPU/Mem)</strong> : Ajouter des blocks <code>resources.requests</code> et <code>resources.limits</code> sur chaque conteneur.</li>
                <li><strong>POLICY 8 (Labels)</strong> : Mettre à jour les metadata de vos déploiements pour injecter les labels standards exigés.</li>
            </ul>
        </div>
    </div>
</body>
</html>
'''

with open(html_path, 'w') as f:
    f.write(html_content)

print(f'[OK] HTML report written to {html_path}')
print(f'[STATS] Compliance Score: {compliance_score}% ({compliant_pods_count}/{total_pods} pods conformes)')
"

echo "=== AUDIT COMPLETED ==="
echo "Report is available at: $REPORT_HTML"
