apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: securerag-hub
resources:
  - ../../base
configMapGenerator:
  - name: securerag-common-config
    behavior: merge
    literals:
      - APP_ENV=staging
      - APP_DEBUG=false
      - FEATURE_MULTI_CLUSTER=false
      - FEATURE_OTEL_ENABLED=true
      - FEATURE_CANARY_ENABLED=false
images:
  - name: ghcr.io/example/securerag-hub-portal-web
    newName: localhost:5001/securerag-hub-portal-web
    newTag: demo
  - name: ghcr.io/example/securerag-hub-auth-users
    newName: localhost:5001/securerag-hub-auth-users
    newTag: demo
