apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prometheus-rbac.yaml
  - prometheus-config.yaml
  - prometheus-rules.yaml
  - prometheus-rules-security.yaml      # P1-13 alertes sécurité
  - prometheus-deployment.yaml
  - grafana-deployment.yaml
  - grafana-dashboards.yaml             # P1-14 dashboards SRE/Sécurité
  - grafana-dashboards-extra.yaml
  - loki-deployment.yaml
  - promtail.yaml
  - alertmanager.yaml
  - alertmanager-external-secret.yaml
  - networkpolicy.yaml
  - kube-state-metrics.yaml
  - tempo/tempo-deployment.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: securerag-hub
      app.kubernetes.io/component: observability
    includeSelectors: false

