apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-auth
  namespace: securerag-hub
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: auth_users
      owner: securerag
