apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: securerag-database-secrets
  namespace: securerag-backup
  labels:
    app.kubernetes.io/name: postgres-backup
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: securerag-database-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        DB_HOST: "postgres-auth.securerag-hub.svc.cluster.local"
        DB_PORT: "5432"
        DB_USERNAME: "securerag"
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
        DB_SSLMODE: "disable"
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: securerag/common-secrets
        property: DB_PASSWORD
