apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: securerag-backup
resources:
  - namespace.yaml
  - pvc.yaml
  - cronjob-postgres.yaml
  - database-external-secret.yaml
  - s3-backup-credentials.yaml
  - networkpolicy.yaml
  - etcd-backup-cronjob.yaml
  - vault-backup-cronjob.yaml
  - argocd-backup-cronjob.yaml
  - argocd-backup-rbac.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: securerag-hub
      app.kubernetes.io/component: backup
