apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: securerag-backup
resources:
  - namespace.yaml
  - pvc.yaml
  - cronjob-postgres.yaml
  - networkpolicy.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: securerag-hub
      app.kubernetes.io/component: backup
