apiVersion: v1
kind: Namespace
metadata:
  name: securerag-backup
  labels:
    name: securerag-backup
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    app.kubernetes.io/part-of: securerag-hub
    app.kubernetes.io/component: backup
