apiVersion: v1
kind: Secret
metadata:
  name: s3-backup-credentials
  namespace: securerag-backup
  labels:
    app.kubernetes.io/name: backup
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin"
  ENCRYPTION_PASSWORD: "BackupPass123!"
