# Ansible - Inventaire de Production pour SecureRAG Hub
# Les adresses IP doivent correspondre aux instances provisionnées par Terraform.

[control-plane]
cp01 ansible_host=10.0.10.10 node_id=1
cp02 ansible_host=10.0.11.10 node_id=2
cp03 ansible_host=10.0.12.10 node_id=3

[workers]
worker01 ansible_host=10.0.10.21
worker02 ansible_host=10.0.11.22
worker03 ansible_host=10.0.12.23

[k8s-cluster:children]
control-plane
workers

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/securerag-deploy-key
ansible_python_interpreter=/usr/bin/python3
