---
- name: Add Prometheus Community Helm repo
  command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  failed_when: false
  run_once: true

- name: Update Helm repositories
  command: helm repo update
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  run_once: true

- name: Deploy kube-prometheus-stack
  command: |
    helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
      --namespace monitoring \
      --create-namespace \
      --set grafana.adminPassword=admin
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  failed_when: false
  run_once: true
