apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: audit-security-service-network
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: audit-security-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: portal-web
      ports:
        - protocol: TCP
          port: 8000
  egress: []
