apiVersion: v1
kind: Service
metadata:
  name: audit-security-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: audit-security-service
  ports:
    - name: http
      port: 8000
      targetPort: http
