apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: securerag-hub

resources:
  - namespace.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - networkpolicy-default-deny.yaml
  - networkpolicy-allow-dns.yaml
  - networkpolicy-validation-ingress.yaml
  - networkpolicy-validation-egress.yaml
  - rbac-runtime-readonly.yaml
  - validation/serviceaccount.yaml

  - portal-web/serviceaccount.yaml
  - portal-web/deployment.yaml
  - portal-web/service.yaml
  - portal-web/networkpolicy.yaml
  - portal-web/pdb.yaml
  - portal-web/hpa.yaml

  - auth-users/serviceaccount.yaml
  - auth-users/deployment.yaml
  - auth-users/service.yaml
  - auth-users/networkpolicy.yaml
  - auth-users/pdb.yaml

  - chatbot-manager/serviceaccount.yaml
  - chatbot-manager/deployment.yaml
  - chatbot-manager/service.yaml
  - chatbot-manager/networkpolicy.yaml
  - chatbot-manager/pdb.yaml

  - conversation-service/serviceaccount.yaml
  - conversation-service/deployment.yaml
  - conversation-service/service.yaml
  - conversation-service/networkpolicy.yaml
  - conversation-service/pdb.yaml

  - audit-security-service/serviceaccount.yaml
  - audit-security-service/deployment.yaml
  - audit-security-service/service.yaml
  - audit-security-service/networkpolicy.yaml
  - audit-security-service/pdb.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: securerag-hub
    includeSelectors: true
    includeTemplates: true
