apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-validation-ingress
  namespace: securerag-hub
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - portal-web
          - auth-users
          - chatbot-manager
          - conversation-service
          - audit-security-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              job-role: validation
      ports:
        - protocol: TCP
          port: 8000
