apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-validation-egress
  namespace: securerag-hub
spec:
  podSelector:
    matchLabels:
      job-role: validation
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - api-gateway
                  - auth-users
                  - chatbot-manager
                  - llm-orchestrator
                  - security-auditor
                  - knowledge-hub
      ports:
        - protocol: TCP
          port: 8080
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ollama
      ports:
        - protocol: TCP
          port: 11434
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: qdrant
      ports:
        - protocol: TCP
          port: 6333
