apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: securerag-runtime-readonly
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - events
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: securerag-runtime-readonly-audit-security-service
subjects:
  - kind: ServiceAccount
    name: sa-audit-security-service
    namespace: securerag-hub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: securerag-runtime-readonly
