apiVersion: v1
kind: ResourceQuota
metadata:
  name: securerag-hub-quota
spec:
  hard:
    pods: "30"
    services: "20"
    persistentvolumeclaims: "10"
    requests.cpu: "3"
    limits.cpu: "8"
    requests.memory: 3Gi
    limits.memory: 8Gi
    requests.ephemeral-storage: 4Gi
    limits.ephemeral-storage: 12Gi
    requests.storage: 40Gi
