# Secret applicatif commun par environnement, injecté depuis Vault via ESO.
# Chaque namespace possède son propre objet Secret (isolation inter-env).
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: securerag-common-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: securerag-common-secrets
  dataFrom:
    - extract:
        key: securerag/common-secrets
