apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: securerag-hub

resources:
  - ../../base

configMapGenerator:
  - name: securerag-common-config
    envs:
      - configmap-env.env

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: ghcr.io/example/securerag-hub-api-gateway
    newName: localhost:5001/securerag-hub-api-gateway
    newTag: dev
  - name: ghcr.io/example/securerag-hub-auth-users
    newName: localhost:5001/securerag-hub-auth-users
    newTag: dev
  - name: ghcr.io/example/securerag-hub-chatbot-manager
    newName: localhost:5001/securerag-hub-chatbot-manager
    newTag: dev
  - name: ghcr.io/example/securerag-hub-llm-orchestrator
    newName: localhost:5001/securerag-hub-llm-orchestrator
    newTag: dev
  - name: ghcr.io/example/securerag-hub-security-auditor
    newName: localhost:5001/securerag-hub-security-auditor
    newTag: dev
  - name: ghcr.io/example/securerag-hub-knowledge-hub
    newName: localhost:5001/securerag-hub-knowledge-hub
    newTag: dev

patches:
  - target:
      kind: Service
      name: api-gateway
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30080
  - target:
      kind: Deployment
      name: api-gateway
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
  - target:
      kind: Deployment
      name: auth-users
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
  - target:
      kind: Deployment
      name: chatbot-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
  - target:
      kind: Deployment
      name: llm-orchestrator
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
  - target:
      kind: Deployment
      name: security-auditor
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
  - target:
      kind: Deployment
      name: knowledge-hub
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
