apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: securerag-hub

resources:
  - ../../base

configMapGenerator:
  - name: securerag-common-config
    envs:
      - configmap-env.env

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: ghcr.io/example/securerag-hub-portal-web
    newName: localhost:5001/securerag-hub-portal-web
    newTag: dev
  - name: ghcr.io/example/securerag-hub-auth-users
    newName: localhost:5001/securerag-hub-auth-users
    newTag: dev
  - name: ghcr.io/example/securerag-hub-chatbot-manager
    newName: localhost:5001/securerag-hub-chatbot-manager
    newTag: dev
  - name: ghcr.io/example/securerag-hub-conversation-service
    newName: localhost:5001/securerag-hub-conversation-service
    newTag: dev
  - name: ghcr.io/example/securerag-hub-audit-security-service
    newName: localhost:5001/securerag-hub-audit-security-service
    newTag: dev

patches:
  - target:
      kind: Service
      name: portal-web
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30081
  - target:
      kind: Deployment
      name: portal-web
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
  - target:
      kind: Deployment
      name: auth-users
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
  - target:
      kind: Deployment
      name: chatbot-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
  - target:
      kind: Deployment
      name: conversation-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
  - target:
      kind: Deployment
      name: audit-security-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
