apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: securerag-verify-cosign-images
  annotations:
    policies.kyverno.io/title: Verify Image Signature Key Static
    policies.kyverno.io/category: Software Supply Chain Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Verifies OCI image signatures using static public key validation.
spec:
  validationFailureAction: Enforce
  background: false
  webhookTimeoutSeconds: 30
  rules:
    - name: verify-image-signature-key
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - securerag-hub
      verifyImages:
        - imageReferences:
            - "registry.securerag.local/*"
            - "localhost:5001/securerag-hub-*"
          required: true
          mutateDigest: true
          verifyDigest: true
          attestors:
            - count: 1
              entries:
                - keys:
                    publicKeys: |
                      -----BEGIN PUBLIC KEY-----
                      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEWi542BhMHqQ+sAD+XHASRdZByUHM
                      LwDszD5/eaF50VMBNTOVixQIRxnzMxwNnk8xiWpyr5ctmVRXJr1Ix8lAHA==
                      -----END PUBLIC KEY-----


