apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: securerag-require-image-digest-audit
  annotations:
    policies.kyverno.io/title: Require Image Digest (Audit)
    policies.kyverno.io/category: Software Supply Chain Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      All images must be referenced by their SHA256 digest (e.g. registry.securerag.local/image@sha256:abc123) to prevent tag mutation.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-image-digest
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - securerag-hub
                - recette
      validate:
        message: "All images must be referenced by their SHA256 digest (e.g. registry.securerag.local/image@sha256:abc123)."
        foreach:
          - list: "request.object.spec.containers[]"
            pattern:
              image: "*@sha256:*"
          - list: "request.object.spec.initContainers[] || []"
            pattern:
              image: "*@sha256:*"
