apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-ingress
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal-dns
spec:
  podSelector: {}
  policyTypes: [Egress]
  egress:
  - to: []
    ports: [{port: 53, protocol: UDP}, {port: 53, protocol: TCP}]
