apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-sa
  namespace: securerag-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: env-only-list
  namespace: securerag-prod
rules:
- apiGroups: [""]
  resources: ["pods","services"]
  verbs: ["get","list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","list"]
