apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: qdrant-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: qdrant
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: knowledge-hub
      ports:
        - protocol: TCP
          port: 6333
  egress: []
