apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: chatbot-manager-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: chatbot-manager
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: portal-web
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: auth-users
      ports:
        - protocol: TCP
          port: 8000
