apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: securerag-hub
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
configMapGenerator:
  - name: securerag-common-config
    behavior: merge
    literals:
      - APP_ENV=dr
      - APP_DEBUG=false
      - DR_MODE=true
