apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spire-server-role
rules:
  # Allow SPIRE Server to validate PSAT node tokens
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  # Allow SPIRE Server Workload Registrar to read nodes, pods, configmaps
  - apiGroups: [""]
    resources: ["nodes", "pods", "endpoints", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spire-server-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spire-server-role
subjects:
  - kind: ServiceAccount
    name: spire-server
    namespace: spire-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spire-agent-role
rules:
  # Allow SPIRE Agent to read pods/nodes to attest workloads
  - apiGroups: [""]
    resources: ["pods", "nodes", "nodes/proxy"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spire-agent-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spire-agent-role
subjects:
  - kind: ServiceAccount
    name: spire-agent
    namespace: spire-system
